keys:
  - &volt_cluster age1tf6hky66y70lgkd9petf5tzempxltsh2kpe0nqs696ascnyyk5eqfvyyuh
  - &personal age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0

creation_rules:
  - path_regex: k8s/secrets/.*\.sops\.yaml$
    key_groups:
      - age:
          - *volt_cluster
          - *personal
