apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghcr-pull
    namespace: yt-dlp-api
spec:
    secretTemplates:
        - name: ghcr-pull
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:MpuynW5gwl+nb1pCeNRZcBdXurFWxfXjADxXwBG5hCw8+7O71hBncInfUom4QjdWoPGTfWdh6Dyd555GWjeqAm5XXoEZtxKHqAy7BYG9jrRnOIhICEmrafb8MprgTkpQhH3NwjPskaqZjRY4nGKDb+vP47dhekZPPniP0gdt0Q4Wb6o0nvgrTnRYm+iG5sy3Y1BenLOKJTkZFsWPzR9f7RvpR3fc2hSke7Z2h7FfosqqvQett9Lu/2qvynB0b0zjXIScrny07HTcgxwUEccO,iv:rQNmA8rhungDfRoJG1Ag6dLu0EJS4Ng0KEVQp+4D0uk=,tag:hjZHycaxNK1Xwvm8sexDBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TFZ0WWdYdnNCdTViNG5F
            MldQbkVGam9ONktQNUFVMVYzNXFwSmJGZUdJCmU0ZjQxMkNOUWk5Nzlxb3ZpZk9i
            bk9NbktWU2lqUGMrSW9WWjVPRUZPcWcKLS0tIEtaMTJDRENVbnR6TkZQVXNZMmVH
            MHB4OXI0L0Fjc2p3QzB6MGNyS1c1NmcKObBdyKvFUxiEY5+sybZvjv5fA5p+VIGO
            P7gDt4m7qBg1pOVjiyNWZGq2Qrg0WYDXClt37lGuwygKkqO/OFp9Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tf6hky66y70lgkd9petf5tzempxltsh2kpe0nqs696ascnyyk5eqfvyyuh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZHFDa3ljb25qL2JPdDFT
            cnRlM1VQbHlVMGR2Z3JHcWpUSlJWV1c3b1FnClZWU1RXRWtEU01TZkdsQlZvZjV3
            YVJQYSs5cWVZL2hxdUdSWm9ZV0RSTkkKLS0tIHloY0NCTWhVNm9vdStJNXBNbkpU
            c0lXbFpvYURtWTh5TDJmY3Q2cGp2ekUK65O52EXjRZDijt4QYpHpmoN07oQ6YWhh
            cSLVdQ7eq7e1sP7TbkXzqNG0yo2rSIGoroNYJUvjuZGDnU2eyv+E6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T18:26:58Z"
    mac: ENC[AES256_GCM,data:K3ZMMQ67Ey7z4Co2wqo3AnN1cG2x+a5aAgiypY6nKd50yjHUR/kNvtdmvKGqdVMmEB8KQQjSUTw6RrJi/aBP0l5i5uR1G4H38F6tuFT46V7FwJuN7b7932aWlZktWfch+0tfCpa5INOMZ9MMLoxQ+LRpxqCOeeP5Crpd8lY2BD8=,iv:fgksWqwAKLfSSZ3PTTGNBhJakT40tLIi58WB6N7ph/8=,tag:XzZ3l5/S5gNNDbl2QGvEBQ==,type:str]
    version: 3.13.0
