apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: yt-dlp-api-ts
    namespace: yt-dlp-api
spec:
    secretTemplates:
        - name: yt-dlp-api-ts
          type: Opaque
          stringData:
            #ENC[AES256_GCM,data:TOWj80V6Lx8V/BrPuAOleFuV5wrIGdMv7K5jdMER88YuZMgV3NNfLt15+Xm7wpHadMO0fWreXF6+cr3CDHb+xNpXOw==,iv:GT8aNlwzAvASyITgVhDktpiktQp6Wkj38dsQjVkeno0=,tag:U3FUhu2EsBiKZ0aDfrNiiw==,type:comment]
            #ENC[AES256_GCM,data:dnqWdyDS1SgxPXLsxEGshnv3AQ74YFX2c6oQJEZGikef0d5QtDXFcR4bd/Qx+YzrrVLSl8gSml4bNBkIBEKxhZ1qKusmRWs=,iv:NCJAW8HRh4DLQ3hFOLqheWxZCAyaqz/gMb6YBcm+OME=,tag:x1/Ws+LZwmdbIFp7Dt2+vw==,type:comment]
            #ENC[AES256_GCM,data:B+WQsV//hftwAkZqDYlAzCFDOcPJXqE6FMjUB0EAtTKYOmuWqwhvW94/XQ4dFjH9LqYI5mqz4ezRDw9NV7Wm,iv:oK89kV4seXyV1clMx0k9CZQh3IT31dPTiSsAmIJbspk=,tag:InScn9+0qLPniLnBLyksug==,type:comment]
            #ENC[AES256_GCM,data:QbYb5BHWQIgR4us+jDXYU30IZ2uNolN7xcuIL1l+OpjeJz0e,iv:HsHROuaz+RGNdx9wuXrOZDTfOdfpxTapGYHp81LuH/w=,tag:bOcZ9+/EOU3beo14vupXhQ==,type:comment]
            authkey: ENC[AES256_GCM,data:agrADwVaGqjf2nZpjE9eXIjSnOWknDpdu7kyev+vMTtnsDJytDh9mpT+faIC1RFBZ0lgcvSy9JKegnO5G9RbFFs31Ll/bsNyVcO4ivu8rjp1+xZXsgMrQA==,iv:Rspu8QyUY70t+hXm5BtHrhPL5DOrmaBCX6DQbHpRl8o=,tag:UUDw1UNqrKz9JKG5XKA5Zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeFVnelRxSklvM1RvQ0lY
            SnErZzZWU2dSdjg5akQvRWJIWStMY3BtckJBCnQ1ZHo0YnIyVUp0NUtmTEFWRjZx
            Yk5SL0RKLzZKamN2RklDc1QwZ0JGOFUKLS0tIDNPMzZhekhPOVpTd1ZMWnFpbXY5
            Y1RQdFVscjZDbGw2NFd5TXMyYy9xNU0KT+CDeZVqhHDWIRQ3jfh/4lwENk4zIcra
            6eRUQykFpLj7WTQtYiorzTngvLNxdjsZ+/5SbErL2UkG65E65r/9SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tf6hky66y70lgkd9petf5tzempxltsh2kpe0nqs696ascnyyk5eqfvyyuh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RnlQdnpkUEtCZVo5MFJO
            QnpXaUpXYzVpY3NoNVloMzRVbHZscjVEYzNJCkttNXVvQ0x0NmdCZWNPMUZYMjg0
            R0xZWW1Xd1k3blVrb09DY1FnbW40Sk0KLS0tIDRGb3VpaFFuNkVkWW9PTDVCTkVr
            bHlCZXlKdzZzZVZNVVpsd2JJaUdOZXMKSy7yx4qG94rFv/sdBAMgC+F/azkfXwsW
            bw4UMyP//PMZuf0chUJv3nC7SkKaqWXCNu8GIuIzryJ2EmZuIp4BFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T18:25:00Z"
    mac: ENC[AES256_GCM,data:GvTa8BoHlOOckSAx8eWGz9j3YQ0qKI9EpkwnlCWgjLnt4OpiFAQkGRSRDtP2dY6mCjA6H63nP5z+4JVvjcW4mL5/AyIdF/KSPdSS+7TX22xdT8KOfxjXRZ7/buuxoxca0q58cS4wCFT0DSW97NzWt0xQuvn5m+NOTA3o4+wUOUw=,iv:7xrdECp0lZ/omGp8X08jziJaiFvnu2FXpT+f/YsI/14=,tag:v8Mjr/2JF4aTv5Jdsj2DTw==,type:str]
    version: 3.13.0
