apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - secrets/ghcr-pull.sops.yaml
  - secrets/ts.sops.yaml

images:
  - name: ghcr.io/andreivolt/yt-dlp-api
    newTag: latest
